### ISSUE TITLE
Update auth charts to include the CORS changes

### ISSUE THREAD

**Issue by dbampalikis** [neicnordic/sda-helm#146]
The current version of the helm charts doesn't include the changes introduced with [this pull request](https://github.com/neicnordic/sda-auth/commit/8dd9f66485d07fcdb2f294eeaa6130729837f685) and therefore the auth is not allowing for logging in with EGA accounts when deployed

**Comment by norling** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Giant-Sloth-6041ec3fd9297d0016321f73/issues/neicnordic/sda-helm/146?planning-poker) with Zenhub @aaperis @dbampalikis @jbygdell @kostas-kou @viklund
