### ISSUE TITLE
Cache request in nginx ingest for S3proxy

### ISSUE THREAD

**Issue by norling** [neicnordic/sda-helm#159]
To prevent upload problems as we saw in Bigpicture, we need to update the helm charts so that the fix is added to all deployments.

The helm chart should also be deployed to fega.

**Comment by jbygdell** [comment]
`nginx.ingress.kubernetes.io/proxy-request-buffering: "on"`

**Comment by norling** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Giant-Sloth-6041ec3fd9297d0016321f73/issues/neicnordic/sda-helm/159?planning-poker) with Zenhub @aaperis @dbampalikis @jbygdell @kostas-kou @kusalananda @nanjiangshu @viklund
