### ISSUE TITLE
Failing to deploy broker

### ISSUE THREAD

**Issue by t0rrant** [neicnordic/sda-helm#35]
After a successful deployment and noticing I missed setting up some configurations, I tried to upgrade the installed helm chart:

```
helm upgrade broker sda-mq .....
```

after that the broker was in a weird state which led me to recreate the whole k3s cluster, even after that the `broker-sda-mq-0` pod stays in a failed state:

```
root@k3s-master1:~# kubectl get pods
NAME                          READY   STATUS             RESTARTS   AGE
postgres-sda-db-0             1/1     Running            0          98m
cega-mq-7d9684f89-7cjsd       1/1     Running            0          79m
cega-users-67bcb8c8b4-7mdns   1/1     Running            0          79m
broker-sda-mq-0               0/1     CrashLoopBackOff   7          12m
```

after taking a look at the logs:

```
root@k3s-master1:~# kubectl logs broker-sda-mq-0
2020-09-22 14:50:43.332 [error] Unable to parse erlang terms from  RABBITMQ_ADVANCED_CONFIG_FILE file: /var/lib/rabbitmq/advanced.config
                                Error: {76,erl_scan,
                                        {string,34,">>}\n            "}}
```

and I can't seem to replicate this locally by launching a container using the `neicnordic/sda-mq` image.

Am I missing something else?

**Comment by blankdots** [comment]
this is know bug for rabbitmq if you are trying to re-deploy reusing a previous volume that a rabbitmq pod used. I suggest disabling persistence or using a new volume.

**Comment by t0rrant** [comment]
I will try without persistent storage, however I did this on a clean cluster.

I uninstalled the charts by hand `helm delete <name>`, and cleared the persistent volumes via `kubectl delete pvc <pvc-name>` for each dangling pvc (broker and postgres were still present).

Afterwards I configured the sda-mq chart to not use persistent storage, however I still get the same error.

Tomorrow I'll try with different helm/k3s versions to see if I get different results.

Thanks for your input!

**Comment by blankdots** [comment]
also might want to check `/var/lib/rabbitmq/advanced.config` to see if the configuration is valid the repo for that is https://github.com/neicnordic/LocalEGA-mq/ see entrypoint

**Comment by blankdots** [comment]
@t0rrant is this an issue and we can help or we close ?

**Comment by t0rrant** [comment]
I'm currently hitting other issues I believe are related to infra, if I still have the same issues regarding the sda-mq I'll reopen.

Thanks for your inputs!
